### PR TITLE
Desktop ux

### LINKED ISSUE #206: Lockwise Rebranding
## Must Haves
* [ ] Update favicon/toolbar icon (branded)
* [x] Update logo (branded w/ name) #213
* [x] Update product name text #213
* [x] Update text for "entry"/"entries" --> "login"/"logins" #213
* [x] Window Title to full product name #213

## Nice to Haves
* [ ] (Management) Reflow Header Bar (#210)
* [ ] (Management) Reflow list Sidebar (#211)
* [ ] (Management) Reflow Details Panel (#212)

## References
* [Desktop Changes](https://docs.google.com/document/d/1fxgK7PDwnZodUW6XJO0zv7Ozm85DJgzDrmQtqe53XUs/edit#heading=h.woqebvspymga)
* Full Logo ([svg](https://drive.google.com/file/d/1QXyFFw6wXIjqBJnbxpViSvp-vt8F_ZmV/view))
* Icon (svg) (_TBD_)

### PR DESCRIPTION
**Pull request by linuxwolf**
Fixes #206 

All of the rebranding work, previously reviewed in parts against this branch.

## To Do

- [ ] make sure CI builds are passing (e.g.: fix lint and other errors)

### CODE REVIEW

**Comment by flodolo** [comment]
FYI, no trace of notification for the FTL change

**Comment by linuxwolf** [comment]
Thanks for informing.

I'm adding a personal note to explicitly add you to future PRs that touch the FTL files in`src/locales/en-US`.

The other codeowners were definitely informed.  We don't expect more than a couple such PRs.

**Comment by flodolo** [comment]
I'd very much prefer automation to manual. Any chance to look into why CODEOWNERS doesn't work as expected? I see there were some tries to update it in the past days.

**Comment by linuxwolf** [comment]
We were trying, and it seemed to work.  Why it's not for that specific case I don't know.

We don't expect more than another 1 or 2 PRs before all future work shifts to m-c; in my opinion the effort to debug this exceeds the effort to explicitly keep you apprised.

**Comment by flodolo** [comment]
> We don't expect more than another 1 or 2 PRs before all future work shifts to m-c

That's another piece of information that I'm missing :-\

**Pull request merged**
