### PR TITLE
Enable the currently 100% translated languages

### PR DESCRIPTION
**Pull request by devinreams**
https://pontoon.mozilla.org/projects/lockwise-add-on/

Enabled? | Language | Locale | Speakers | Latest Activity | Progress
-- | -- | -- | -- | -- | --
👎 | Chinese (China) | zh-CN | 1,230,741,000 | 6 hours ago | 88%
✅ | Chinese (Taiwan) | zh-TW | 22,244,000 | 6 days, 7 hours ago | 100%
👎  | Czech | cs | 10,431,000 | ― | 0%
✅ | Dutch | nl | 31,184,000 | 2 days, 7 hours ago | 100%
✅ | English (Canada) | en-CA | 30,636,382 | 1 day, 4 hours ago | 100%
✅ | French | fr | 231,632,000 | 1 day, 7 hours ago | 100%
✅ | Frisian | fy-NL | 728,000 | 2 days, 7 hours ago | 100%
✅ | German | de | 107,183,000 | 6 days, 2 hours ago | 100%
✅ | Hungarian | hu | 12,548,000 | 2 days, 2 hours ago | 100%
👎  | Indonesian | id | 164,141,000 | 1 day, 15 hours ago | 45%
✅ | Italian | it | 69,025,000 | 5 days, 14 hours ago | 100%
✅  | Kaqchikel | cak | 450,000 | 4 days, 22 hours ago | 100%
✅  | Norwegian Nynorsk | nn-NO | 1,301,000 | 21 hours ago | 100%
✅  | Portuguese (Brazil) | pt-BR | 185,876,000 | 4 days, 22 hours ago | 100%
✅  | Romanian | ro | 22,511,000 | 5 days, 14 hours ago | 100%
👎  | Slovenian | sl | 1,867,000 | 8 hours ago | 74%
✅ | Swedish | sv-SE | 9,311,000 | 2 days ago | 100%
✅  | Vietnamese | vi | 82,239,000 | 4 days, 8 hours ago | 100%
✅  | Welsh | cy | 522,000 | 1 day, 8 hours ago | 100%

@linuxwolf @Delphine @flodolo since there are so many strings, any concerns with enabling those that aren't yet 100% for next week's release?

### CODE REVIEW

**Comment by flodolo** [comment]
It would really help my brain to have these lists ordered by locales :)

By the time you read this, zh-CN is completed. 

We should exclude cs, id, and sl for now, and plan for another release, maybe in a week? Slovenian will be likely ready by then.

Note that you should sync back the Pontoon branch into master, because we added a new string. Locales at 99% should definitely be enabled.

**Comment by linuxwolf** [comment]
> We should exclude cs, id, and sl for now, and plan for another release, maybe in a week? Slovenian will be likely ready by then.
> 

Will do, thanks.

> Note that you should sync back the Pontoon branch into master, because we added a new string. Locales at 99% should definitely be enabled.

We updated `pontoon` with the latest from `master` just after the string was added, and just updated `master` with the latest from `pontoon`.  It looks like some translators have already picked that up.

**Comment by flodolo** [comment]
> By the time you read this, zh-CN is completed.

zh-CN is still missing.

**Comment by linuxwolf** [comment]
> > By the time you read this, zh-CN is completed.
> 
> zh-CN is still missing.

Thanks for the catch; missed adding it while sorting.

**Comment by linuxwolf** [comment]
All the 100% are enabled, and latest from `pontoon` included here.

**Pull request merged**
