### PR TITLE
Allow for Varying Widths of the Doorhanger

### LINKED ISSUE #152: A white border is wrongly displayed in the Lockwise doorhanger if it's pinned to Overflow menu
[Affected Versions]:
- Lockbox 2.1.0-alpha
- Firefox 66.0.3 and up

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Perquisites]
- Have the latest Firefox 66.0.2 installed.
- Have a Firefox profile with the "xpinstall.signatures.dev-root" pref created and set to "true".
- Have the Lockbox 2.1.0 - alpha extension instaled.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Right click on the Lockbox icon from the toolbar menu.
3. Click the "Pin to Overflow Menu" option from the context menu.
4. Click the "More tools..." button and click the "Lockbox" option.
5. Observe the "Lockbox" doorhanger.

[Expected results]:
- The doorhanger is correctly displayed.

[Actual results]:
- A white border is wrongly displayed in the right part of the doorhager.

[Notes]:
- Attached a recording with the issue:
doorhanger pinned to overflow

### PR DESCRIPTION
**Pull request by linuxwolf**
Fixes #152

This changes the doorhanger from a fixed width to using CSS media queries to fix the width to 300px if the viewport is no bigger than that, or 100% if larger.

## Testing and Review Notes

1. Either pin the Lockwise toolbar to the overflow menu, or narrow the main browser window until Lockwise is moved into an overflow menu
2. Click the overflow menu chevron, then Lockwise

## Screenshots or Videos

**Doorhanger in overflow:**
addon-152 doorhanger-overflow

**Doorhanger in toolbar:**
addon-152 doorhanger-toolbar

## To Do

- [x] add “WIP” to the PR title if pushing up but not complete nor ready for review
- [x] double check the original issue to confirm it is fully satisfied
- [x] add testing notes and screenshots in PR description to help guide reviewers
- [x] request the "UX" team perform a design review (if/when applicable)
- [x] make sure CI builds are passing (e.g.: fix lint and other errors)

### CODE REVIEW

**Comment by 6a68** [comment]
The min-width change looks fine to me. This makes the doorhanger wider than previously in the non-overflowed mode, but I think that might improve usability. The wider doorhanger also matches the width of the library menu, which might be a good thing? 🤷‍♂

**Comment by linuxwolf** [comment]
> The min-width change looks fine to me. This makes the doorhanger wider than previously in the non-overflowed mode, but I think that might improve usability. The wider doorhanger also matches the width of the library menu, which might be a good thing? 🤷‍♂

The width is completely coincidental.  It'll change based on the contents – shorter domains/usernames/passwords will be narrower, longer will be wider.  I'm not sure which is preferred (fixed width and whitespace, or jumping around).

**Comment by 6a68** [comment]
> The width is completely coincidental. It'll change based on the contents – shorter domains/usernames/passwords will be narrower, longer will be wider. I'm not sure which is preferred (fixed width and whitespace, or jumping around).

Ah, I see. I'd guess a fixed width at the size of the overflow menu (377px), but this seems more like a product/UX question to me

**Comment by linuxwolf** [comment]
@sandysage @changecourse @6a68 

Updated description with screencaps in both overflow and toolbar modes.

**Comment by linuxwolf** [comment]
> I'm not very thrilled about our navigation elements jumping around based on the arbitrary length of username and password strings. i'd prefer a fixed width and handling overflows on a second line.

That can be done, but I don't think it can be done in time for May 28.

I'll see what I can do, but the choices likely are:
* Accept the white border on the right side
* Accept the doorhanger jumps around

**cc @sandysage **

**Comment by linuxwolf** [comment]
Media queries to the rescue.  It seems to work pretty well for me now.  See description for screencaps.

**Comment by linuxwolf** [comment]
With the jumping fixed to address @changecourse concerns, will merge now.

**Pull request merged**
