### PR TITLE
Update strings from Pontoon: it

### PR DESCRIPTION
**Pull request by devinreams**
This not only includes a commit with the IT translation, but also includes the typo fix from #259 (from pontoon branch into master branch).

Documented here #258

### CODE REVIEW

**Comment by linuxwolf** [comment]
I am now realizing that for reasons I can no longer remember, supported locales need to added to `src/locales/locales.json` in order to be usable in [production builds](https://github.com/mozilla-lockwise/lockwise-addon/blob/master/src/locales/README.md).

That, or change the assembly script to dynamically build them as they are for development builds.

**Comment by devinreams** [comment]
>supported locales need to added to src/locales/locales.json

@linuxwolf Done. Thank you, I missed that entirely but equally love that it was in the README. Nice work 👏

**Comment by devinreams** [comment]
@flodolo @linuxwolf I just tried changing my browser language to "it" and I didn't pick this up doing `npm run run`. I also changed my entire system to "it" and did not show the strings there either.

@linuxwolf Have we seen a translated version working/appear as expected recently? I do remember seeing French many months ago.. either way, I think we should still merge this in as-is but add locale testing to the QA plan. Can you please help see that through?

**Comment by flodolo** [comment]
I tested one string the other day and it was working fine for me (installed from about:debugging as temporary)

**Comment by devinreams** [comment]
Thanks for confirming @flodolo. @linuxwolf also confirmed it worked as expected for him. I must've made a mistake in how I loaded the extension.

**Pull request merged**
